#!/usr/bin/python
# -*- coding:utf-8 -*-
import sys
import os
import logging

PICDIR = ".\e-Paper\RaspberryPi_JetsonNano\python\pic"
LIBDIR = ".\e-Paper\RaspberryPi_JetsonNano\python\lib"

if not os.path.exists(LIBDIR):
    raise ValueError("Lib not found.")
sys.path.append(LIBDIR)

from waveshare_epd import epd2in9_V2
from PIL import Image,ImageDraw,ImageFont

logging.basicConfig(level=logging.DEBUG)

try:
    logging.info("epd2in9 V2 Demo") 
    epd = epd2in9_V2.EPD()

    logging.info("init and Clear")
    epd.init()
    epd.Clear(0xFF)

    font24 = ImageFont.truetype(os.path.join(PICDIR, 'Font.ttc'), 24)

    # Drawing on the Horizontal image
    logging.info("Drawing on the Horizontal image...")
    Himage = Image.new('1', (epd.height, epd.width), 255)  # 255: clear the frame
    draw = ImageDraw.Draw(Himage)
    draw.text((10, 0), 'Hello world', font=font24, fill=0)
    epd.display(epd.getbuffer(Himage))

    logging.info("Goto Sleep...")
    epd.sleep()

except IOError as e:
    logging.info(e)

except KeyboardInterrupt:    
    logging.info("ctrl + c:")
    epd2in9_V2.epdconfig.module_exit()
    exit()
